backend:
  name: git-gateway # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: vagr9k/gatsby-advanced-starter # Repo for pushing new commits. Make sure to replace with your repo!
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: blog-post,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: " Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
        }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "home",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "CTA text"
                widget: "string"
              - name: "ctaLink"
                label: "CTA Link"
                widget: "string"
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "contact-page",
            }
          - {
              label: "Slug",
              name: "slug",
              widget: "hidden",
              default: "/contact",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: headerNavigationLinks
        label: Header Links
        file: "data/navigationLinks.json"
        fields:
          - label: Links
            name: headers
            required: true
            widget: list
            minimize_collapsed: true
            fields:
              - { label: "title", name: "title", widget: "string" }
              - { label: "link", name: "link", widget: "string" }
      - name: general
        label: General
        file: "data/site.json"
        fields:
          - label: Site Title
            name: siteTitle
            widget: string
            required: true
          - label: Site Title Short
            name: siteTitleShort
            widget: string
            required: true
          - label: Site Description
            name: siteDescription
            widget: string
            required: true
          - label: Logo
            name: siteLogo
            widget: image
            default: "/logos/logo-1024.png"
          - label: Site Url
            name: siteUrl
            widget: string
            required: true
          - label: Path Prefix
            name: pathPrefix
            widget: string
            required: true
          - label: Site RSS Title
            name: siteRssTitle
            widget: string
            required: true
          - label: siteFBAppID
            name: siteFBAppID
            widget: string
            required: true
          - label: googleAnalyticsID
            name: googleAnalyticsID
            widget: string
            required: true
          - label: disqusShortname
            name: disqusShortname
            widget: string
            required: true
          - label: dateFromFormat
            name: dateFromFormat
            widget: string
            required: true
          - label: dateFormat
            name: dateFormat
            widget: string
            required: true
          - label: postsPerPage
            name: postsPerPage
            widget: string
            required: true
          - label: userName
            name: userName
            widget: string
            required: true
          - label: userEmail
            name: userEmail
            widget: string
            required: true
          - label: userPhone
            name: userPhone
            widget: string
            required: true
          - label: userTwitter
            name: userTwitter
            widget: string
            required: true
          - label: userLocation
            name: userLocation
            widget: string
            required: true
          - label: userAvatar
            name: userAvatar
            widget: image
            required: true
          - label: Social Links
            name: socialLinks
            required: true
            widget: list
            minimize_collapsed: true
            fields:
              - { label: "name", name: "name", widget: "string" }
              - { label: "link", name: "link", widget: "string" }
              - { label: "icon", name: "icon", widget: "image" }
          - label: Copyright Text
            name: copyright
            widget: string
            required: true
